#!/bin/sh
[ -z "$1" ] && exit 1 || DIR=$1

MOUNT_OPTS="$3"
echo "$MOUNT_OPTS" | grep -q '\brw\b'
IS_RW=$?

if [ $IS_RW -eq 0 ]; then
  /bin/mount --bind ${DIR}_org ${DIR}
else
  /bin/mount -t tmpfs ramdisk ${DIR}_rw
  /usr/bin/unionfs-fuse -o cow,allow_other,suid,dev,nonempty ${DIR}_rw=RW:${DIR}_org=RO ${DIR}
fi
